// Generated by Selenium IDE
const { Builder, By } = require("selenium-webdriver");
const assert = require("assert");

describe("Cadastro de Segurança", function () {
  this.timeout(30000);
  let driver;
  let vars;

  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();

    vars = {};
  });

  afterEach(async function () {
    setTimeout(async () => {
      await driver.quit();
    }, 1000);
  });

  it("Cadastro de Segurança", async function () {
    await driver.get("http://localhost:3000/");
    await driver.findElement(By.id("login-cadastro")).click();
    await driver.findElement(By.id("modal-cadastro-nome-input")).click();
    await driver
      .findElement(By.id("modal-cadastro-nome-input"))
      .sendKeys("Segurança Teste");
    await driver
      .findElement(By.id("modal-cadastro-tipo-usuario-input"))
      .click();
    await driver
      .findElement(By.css(".component-select-single-option:nth-child(2)"))
      .click();
    await driver
      .findElement(
        By.css("#modal-cadastro-confirmar > .component-button-label")
      )
      .click();
    {
      console.log('manage ',driver);
      // await new Promise((r) => setTimeout(r, 1000));
      const elements = await driver.findElements(
        By.css("#header-usuario-button")
      );
      console.log("elements: ", elements);
      console.log("elements: ", elements.length);
      assert(elements && elements.length);
    }
  });
});
